#!/usr/bin/env python3
# encoding: utf-8
#
# Copyright (c) 2016 Doug Hellmann.  All rights reserved.
# Written for https://pymotw.com
#
"""Done callbacks."""

# end_pymotw_header
from concurrent import futures


def task(n):
    print("{}: starting".format(n))
    raise ValueError("the value {} is no good".format(n))


ex = futures.ThreadPoolExecutor(max_workers=2)
print("main: starting")
f = ex.submit(task, 5)

error = f.exception()
print("main: error: {}".format(error))

try:
    result = f.result()
except ValueError as e:
    print('main: saw error "{}" when accessing result'.format(e))

"""
main: starting
5: starting
main: error: the value 5 is no good
main: saw error "the value 5 is no good" when accessing result

"""
